-- 테이블 삭제
DROP TABLE F_LIKED;
DROP TABLE F_CMT;
DROP TABLE F_IMAGE;
DROP TABLE F_BOARD;
DROP TABLE C_LIKED;
DROP TABLE C_ATTACH;
DROP TABLE C_IMAGE;
DROP TABLE C_CMT;
DROP TABLE C_BOARD;
DROP TABLE Q_CMT;
DROP TABLE Q_BOARD;
DROP TABLE REDBELL;
DROP TABLE S_MEMBER;
DROP TABLE S_ZZIM;
DROP TABLE S_CMT;
DROP TABLE S_GROUP;
DROP TABLE ACCESS_LOG;
DROP TABLE RETIRE_USERS;
DROP TABLE USERS;
DROP TABLE SLEEP_USERS;

-- 테이블 생성
CREATE TABLE USERS (
	USERS_NO	NUMBER	NOT NULL,
	ID	VARCHAR2(50)	NOT NULL UNIQUE,
	NICKNAME	VARCHAR2(20)	NOT NULL UNIQUE,
	PW	VARCHAR2(64)	NOT NULL,
	NAME	VARCHAR2(50)	NOT NULL,
	GRADE	NUMBER	NULL,	-- 관리자:0 스터디장:1  일반 : 2
	GENDER	VARCHAR2(1)	NOT NULL,	-- M, F
	EMAIL	VARCHAR2(50)	NOT NULL UNIQUE,
	MOBILE	VARCHAR2(11)	NOT NULL,
	BIRTHYEAR	VARCHAR2(4)	NOT NULL,
	BIRTHDAY	VARCHAR2(4)	NOT NULL,
	POSTCODE	VARCHAR2(5)	NULL,
	ROAD_ADDRESS	VARCHAR2(100)	NULL,
	JIBUN_ADDRESS	VARCHAR2(100)	NULL,
	DETAIL_ADDRESS	VARCHAR2(100)	NULL,
	EXTRA_ADDRESS	VARCHAR2(100)	NULL,
	AGREE_CODE	NUMBER	NOT NULL,
	SNS_TYPE	VARCHAR2(10)	NULL,
	JOIN_DATE	DATE	NOT NULL,
	PW_MODIFY_DATE	DATE	NULL,	-- 첫 수정일은 회원가입 당시 SYSDATE 비번 마지막 변경일자 + 3개월 마다 변경 안내창 띄우기
	INFO_MODIFY_DATE	DATE	NULL,
	SESSION_ID	VARCHAR2(32)	NULL,
	SESSION_LIMIT_DATE	DATE	NULL,
	BLACK_CNT	NUMBER	NULL,	-- 유저가 신고당한 횟수
	USER_STATE	NUMBER	NOT NULL	-- 일반회원(1) / 제재회원(0) 구분
);

CREATE TABLE ACCESS_LOG (
	ACCESS_LOG_NO	NUMBER	NOT NULL,
	ID	VARCHAR2(50)	NOT NULL UNIQUE,
	LAST_LOGIN_DATE	DATE	NOT NULL
);

CREATE TABLE RETIRE_USERS (
	USER_NO	NUMBER	NOT NULL,
	ID	VARCHAR2(50)	NOT NULL UNIQUE,
	JOIN_DATE	DATE	NULL,
	RETIRE_DATE	DATE	NULL
);

CREATE TABLE SLEEP_USERS (
	USER_NO	NUMBER	NOT NULL,
	ID	VARCHAR2(50)	NOT NULL UNIQUE,
	PW	VARCHAR2(64)	NOT NULL,
	NAME	VARCHAR2(50)	NOT NULL,
	GENDER	VARCHAR2(1)	NOT NULL,
	EMAIL	VARCHAR2(50)	NOT NULL UNIQUE,
	MOBILE	VARCHAR2(11)	NOT NULL,
	JOIN_DATE	DATE	NULL,
	LAST_LOGIN_DATE	DATE	NULL,
	SLEEP_DATE	DATE	NULL
);

CREATE TABLE F_BOARD (
	F_NO	NUMBER	NOT NULL,
	NICKNAME	VARCHAR2(20)	NOT NULL UNIQUE,
	F_TITLE	VARCHAR2(300)	NOT NULL,
	F_CONTENT	VARCHAR2(4000)	NULL,
	F_CREATE_DATE	DATE	NOT NULL,
	F_MODIFY_DATE	DATE	NOT NULL,
	F_HIT	NUMBER	NOT NULL,
	F_IP	VARCHAR2(20)	NOT NULL
);

CREATE TABLE F_IMAGE (
	F_NO	NUMBER	NOT NULL,
	FILESYSTEM	VARCHAR2(40)	NULL
);

CREATE TABLE F_CMT (
	F_CMT_NO	NUMBER	NOT NULL,
	F_NO	NUMBER	NOT NULL,
	NICKNAME	VARCHAR2(20)	NOT NULL UNIQUE,
	F_CMT_CONTENT	VARCHAR2(200)	NOT NULL,
	F_CMT_CREATE_DATE	DATE	NOT NULL,
	F_CMT_MODIFY_DATE	DATE	NOT NULL,
	F_STATE	NUMBER	NOT NULL,	-- 정상 1, 삭제 0
	F_DEPTH	NUMBER	NOT NULL,	-- 댓글 0, 댓글의 답글 1
	F_IP	VARCHAR2(20)	NOT NULL
);

CREATE TABLE F_LIKED (
	F_NO	NUMBER	NOT NULL,
	NICKNAME	VARCHAR2(20)	NOT NULL UNIQUE
);

CREATE TABLE C_BOARD (
	C_NO	NUMBER	NOT NULL,
	NICKNAME	VARCHAR2(20)	NOT NULL UNIQUE,
	C_TITLE	VARCHAR2(300)	NOT NULL,
	C_CONTENT	VARCHAR2(4000)	NULL,
	C_CREATE_DATE	DATE	NOT NULL,
	C_MODIFY_DATE	DATE	NOT NULL,
	C_HIT	NUMBER	NOT NULL,
	C_IP	VARCHAR2(20)	NOT NULL
);

CREATE TABLE C_IMAGE (
	C_NO	NUMBER	NOT NULL,
	FILESYSTEM	VARCHAR2(40)	NULL
);

CREATE TABLE C_ATTACH (
	ATTACH_NO	NUMBER	NOT NULL,
	C_NO	NUMBER	NOT NULL,
	PATH	VARCHAR2(300)	NULL,	-- 파일의 경로
	ORIGIN	VARCHAR2(300)	NULL,	-- 원본이름
	FILESYSTEM	VARCHAR2(40)	NULL,	-- 파일의 저장된 이름
	DOWNLOAD_CNT	NUMBER	NULL
);

CREATE TABLE C_CMT (
	C_CMT_NO	NUMBER	NOT NULL,
	C_NO	NUMBER	NOT NULL,
	NICKNAME	VARCHAR2(20)	NOT NULL UNIQUE,
	C_CMT_CONTENT	VARCHAR2(200)	NOT NULL,
	C_CMT_CREATE_DATE	DATE	NOT NULL,
	C_CMT_MODIFY_DATE	DATE	NOT NULL,
	C_STATE	NUMBER	NOT NULL,	-- 정상 1, 삭제 0
	C_DEPTH	NUMBER	NOT NULL,	-- 댓글 0, 댓글의 답글 1
	C_IP	VARCHAR2(20)	NOT NULL
);

CREATE TABLE C_LIKED (
	F_NO	NUMBER	NOT NULL,
	NICKNAME	VARCHAR2(20)	NOT NULL UNIQUE
);

CREATE TABLE Q_BOARD (
	Q_NO	NUMBER	NOT NULL,
	NICKNAME	VARCHAR2(20)	NOT NULL UNIQUE,
	Q_TITLE	VARCHAR2(300)	NOT NULL,
	Q_CONTENT	VARCHAR2(4000)	NULL,
	Q_PW	NUMBER	NULL,
	Q_CREATE_DATE	DATE	NOT NULL,
	Q_MODIFY_DATE	DATE	NOT NULL,
	Q_HIT	NUMBER	NOT NULL,
	Q_IP	VARCHAR2(20)	NULL
);

CREATE TABLE Q_CMT (
	Q_CMT_NO	NUMBER	NOT NULL,
	Q_NO	NUMBER	NOT NULL,
	Q_CMT_CONTENT	VARCHAR2(200)	NOT NULL,
	Q_CMT_CREATE_DATE	DATE	NOT NULL,
	Q_CMT_MODIFY_DATE	DATE	NOT NULL,
	Q_STATE	NUMBER	NOT NULL,	-- 정상 1, 삭제 0
	Q_IP	VARCHAR2(20)	NOT NULL
);

CREATE TABLE S_GROUP (
	S_NO	NUMBER	NOT NULL,
	NICKNAME	VARCHAR2(20)	NOT NULL UNIQUE,
	S_TITLE	VARCHAR2(300)	NOT NULL,
	S_CONTENT	VARCHAR2(4000)	NULL,
	S_CREATE_DATE	DATE	NOT NULL,
	S_MODIFY_DATE	DATE	NOT NULL,
	S_HIT	NUMBER	NOT NULL,
	S_GENDER	VARCHAR2(1)	NOT NULL,
	S_REGION	VARCHAR2(300)	NOT NULL,
	S_WIDO	VARCHAR2(30)	NOT NULL,
	S_GDO	VARCHAR2(30)	NOT NULL,
	S_LANG	VARCHAR2(500)	NOT NULL,
	S_PEOPLE	VARCHAR2(50)	NOT NULL,
	S_CONTACT	VARCHAR2(30)	NOT NULL,
	S_DATE	DATE	NOT NULL,
	S_IP	VARCHAR2(20)	NOT NULL
);

CREATE TABLE S_CMT (
	S_CMT_NO	NUMBER	NOT NULL,
	S_NO	NUMBER	NOT NULL,
	NICKNAME	VARCHAR2(20)	NOT NULL UNIQUE,
	S_CMT_CONTENT	VARCHAR2(200)	NOT NULL,
	S_CMT_CREATE_DATE	DATE	NOT NULL,
	S_STATE	NUMBER	NOT NULL,	-- 정상 1, 삭제 0
	S_DEPTH	NUMBER	NOT NULL,	-- 댓글0, 댓글의 답글 1
	S_IP	VARCHAR2(20)	NOT NULL
);

CREATE TABLE S_ZZIM (
	NICKNAME	VARCHAR2(20)	NOT NULL UNIQUE,
	S_NO	NUMBER	NOT NULL
);

CREATE TABLE S_MEMBER (
	NICKNAME	VARCHAR2(20)	NOT NULL UNIQUE,
	S_NO	NUMBER	NOT NULL,
	A_DATE	DATE	NULL,
	A_GUBUN	NUMBER(1)	NULL	-- 대기:0, 확정:1,  취소:2
);

CREATE TABLE REDBELL (
	R_NO NUMBER	NOT NULL,
	ID VARCHAR2(50)	NOT NULL UNIQUE,
	R_CONTENT VARCHAR2(300)	NOT NULL,
	R_DATE	DATE	NOT NULL,
	R_GUBUN	NUMBER(1)	NULL,	-- 스터디번호 : 1 , 댓글번호:2
	R_TARGET NUMBER	NOT NULL	-- FK,FK  스터디게시판 순번과 댓글의 순번을 여기에 FK함
);

-- 기본키
ALTER TABLE USERS 
    ADD CONSTRAINT PK_USERS PRIMARY KEY (USERS_NO);

ALTER TABLE ACCESS_LOG 
    ADD CONSTRAINT PK_ACCESS_LOG PRIMARY KEY (ACCESS_LOG_NO);

ALTER TABLE RETIRE_USERS 
    ADD CONSTRAINT PK_RETIRE_USERS PRIMARY KEY (USER_NO);

ALTER TABLE SLEEP_USERS
    ADD CONSTRAINT PK_SLEEP_USERS PRIMARY KEY (USER_NO);

ALTER TABLE F_BOARD 
    ADD CONSTRAINT PK_F_BOARD PRIMARY KEY (F_NO);

ALTER TABLE F_IMAGE 
    ADD CONSTRAINT PK_F_IMAGE PRIMARY KEY (F_NO);

ALTER TABLE F_CMT 
    ADD CONSTRAINT PK_F_CMT PRIMARY KEY (F_CMT_NO);

ALTER TABLE F_LIKED 
    ADD CONSTRAINT PK_F_LIKED PRIMARY KEY (F_NO);

ALTER TABLE C_BOARD 
    ADD CONSTRAINT PK_C_BOARD PRIMARY KEY (C_NO);

ALTER TABLE C_IMAGE 
    ADD CONSTRAINT PK_C_IMAGE PRIMARY KEY (C_NO);

ALTER TABLE C_ATTACH 
    ADD CONSTRAINT PK_C_ATTACH PRIMARY KEY (ATTACH_NO);

ALTER TABLE C_CMT 
    ADD CONSTRAINT PK_C_CMT PRIMARY KEY (C_CMT_NO);

ALTER TABLE C_LIKED 
    ADD CONSTRAINT PK_C_LIKED PRIMARY KEY (F_NO);

ALTER TABLE Q_BOARD 
    ADD CONSTRAINT PK_Q_BOARD PRIMARY KEY (Q_NO);

ALTER TABLE Q_CMT 
    ADD CONSTRAINT PK_Q_CMT PRIMARY KEY (Q_CMT_NO);

ALTER TABLE S_GROUP 
    ADD CONSTRAINT PK_S_GROUP PRIMARY KEY (S_NO);

ALTER TABLE S_CMT 
    ADD CONSTRAINT PK_S_CMT PRIMARY KEY (S_CMT_NO);
    
ALTER TABLE REDBELL 
    ADD CONSTRAINT PK_REDBELL PRIMARY KEY (R_NO);

-- 외래키
ALTER TABLE ACCESS_LOG 
    ADD CONSTRAINT FK_ACCESS_LOG_USERS FOREIGN KEY (ID)
        REFERENCES USERS (ID);

ALTER TABLE F_BOARD 
    ADD CONSTRAINT FK_F_BOARD_USERS FOREIGN KEY (NICKNAME)
        REFERENCES USERS (NICKNAME)
            ON DELETE SET NULL;

ALTER TABLE F_IMAGE 
    ADD CONSTRAINT FK_F_IMAGE_F_BOARD FOREIGN KEY (F_NO)
        REFERENCES F_BOARD (F_NO)
            ON DELETE CASCADE;

ALTER TABLE F_CMT 
    ADD CONSTRAINT FK_F_CMT_USERS FOREIGN KEY (NICKNAME)
        REFERENCES USERS (NICKNAME)
            ON DELETE SET NULL;

ALTER TABLE F_CMT 
    ADD CONSTRAINT FK_F_CMT_F_BOARD FOREIGN KEY (F_NO)
        REFERENCES F_BOARD (F_NO)
            ON DELETE CASCADE;

ALTER TABLE F_LIKED 
    ADD CONSTRAINT FK_F_LIKED_F_BOARD FOREIGN KEY (F_NO)
        REFERENCES F_BOARD (F_NO)
            ON DELETE CASCADE;

ALTER TABLE C_BOARD 
    ADD CONSTRAINT FK_C_BOARD_USERS FOREIGN KEY (NICKNAME)
        REFERENCES USERS (NICKNAME)
            ON DELETE SET NULL;

ALTER TABLE C_IMAGE 
    ADD CONSTRAINT FK_C_IMAGE_C_BOARD FOREIGN KEY (C_NO)
        REFERENCES C_BOARD (C_NO)
            ON DELETE CASCADE;

ALTER TABLE C_CMT 
    ADD CONSTRAINT FK_C_CMT_USERS FOREIGN KEY (NICKNAME)
        REFERENCES USERS (NICKNAME)
            ON DELETE SET NULL;

ALTER TABLE C_CMT 
    ADD CONSTRAINT FK_C_CMT_C_BOARD FOREIGN KEY (C_NO)
        REFERENCES C_BOARD (C_NO)
            ON DELETE CASCADE;

ALTER TABLE C_LIKED 
    ADD CONSTRAINT FK_C_LIKED_USERS FOREIGN KEY (NICKNAME)
        REFERENCES USERS (NICKNAME)
            ON DELETE SET NULL;

ALTER TABLE C_LIKED 
    ADD CONSTRAINT FK_C_LIKED_C_BOARD FOREIGN KEY (F_NO)
        REFERENCES C_BOARD (C_NO)
            ON DELETE CASCADE;

ALTER TABLE C_ATTACH 
    ADD CONSTRAINT FK_C_ATTACH_C_BOARD FOREIGN KEY (C_NO)
        REFERENCES C_BOARD (C_NO)
            ON DELETE CASCADE;

ALTER TABLE Q_BOARD 
    ADD CONSTRAINT FK_Q_BOARD_USERS FOREIGN KEY (NICKNAME)
        REFERENCES USERS (NICKNAME)
            ON DELETE SET NULL;

ALTER TABLE Q_CMT 
    ADD CONSTRAINT FK_Q_CMT_Q_BOARD FOREIGN KEY (Q_NO)
        REFERENCES Q_BOARD (Q_NO)
            ON DELETE CASCADE;

ALTER TABLE S_GROUP 
    ADD CONSTRAINT FK_S_GROUP_USERS FOREIGN KEY (NICKNAME)
        REFERENCES USERS (NICKNAME)
            ON DELETE CASCADE;

ALTER TABLE S_ZZIM 
    ADD CONSTRAINT FK_S_ZZIM_USERS FOREIGN KEY (NICKNAME)
        REFERENCES USERS (NICKNAME)
            ON DELETE CASCADE;

ALTER TABLE S_ZZIM 
    ADD CONSTRAINT FK_S_ZZIM_S_GROUP FOREIGN KEY (S_NO)
        REFERENCES S_GROUP (S_NO)
            ON DELETE CASCADE;

ALTER TABLE S_CMT 
    ADD CONSTRAINT FK_S_CMT_USERS FOREIGN KEY (NICKNAME)
        REFERENCES USERS (NICKNAME)
            ON DELETE SET NULL;

ALTER TABLE S_CMT 
    ADD CONSTRAINT FK_S_CMT_S_GROUP FOREIGN KEY (S_NO)
        REFERENCES S_GROUP (S_NO)
            ON DELETE CASCADE;

ALTER TABLE S_MEMBER 
    ADD CONSTRAINT FK_S_MEMBER_USERS FOREIGN KEY (NICKNAME)
        REFERENCES USERS (NICKNAME)
            ON DELETE CASCADE;

ALTER TABLE S_MEMBER 
    ADD CONSTRAINT FK_S_MEMBER_S_GROUP FOREIGN KEY (S_NO)
        REFERENCES S_GROUP (S_NO)
            ON DELETE CASCADE;
        
ALTER TABLE REDBELL 
    ADD CONSTRAINT FK_REDBELL_USERS FOREIGN KEY (ID)
        REFERENCES USERS (ID)
            ON DELETE SET NULL;

ALTER TABLE REDBELL 
    ADD CONSTRAINT FK_REDBELL_S_GROUP FOREIGN KEY (R_TARGET)
        REFERENCES S_GROUP (S_NO)
            ON DELETE SET NULL;
        
ALTER TABLE REDBELL 
    ADD CONSTRAINT FK_REDBELL_S_CMT FOREIGN KEY (R_TARGET)
        REFERENCES S_CMT (S_CMT_NO)
            ON DELETE SET NULL;

-- 시퀀스
DROP SEQUENCE USERS_SEQ;
DROP SEQUENCE ACCESS_LOG_SEQ;
DROP SEQUENCE RETIRE_USERS_SEQ;
DROP SEQUENCE SLEEP_USERS_SEQ;
DROP SEQUENCE F_BOARD_SEQ;
DROP SEQUENCE F_IMAGE_SEQ;
DROP SEQUENCE F_CMT_SEQ;
DROP SEQUENCE F_LIKED_SEQ;
DROP SEQUENCE C_BOARD_SEQ;
DROP SEQUENCE C_IMAGE_SEQ;
DROP SEQUENCE C_ATTACH_SEQ;
DROP SEQUENCE C_CMT_SEQ;
DROP SEQUENCE C_LIKED_SEQ;
DROP SEQUENCE Q_BOARD_SEQ;
DROP SEQUENCE Q_CMT_SEQ;
DROP SEQUENCE S_GROUP_SEQ;
DROP SEQUENCE S_CMT_SEQ;
DROP SEQUENCE S_MEMBER_SEQ;
DROP SEQUENCE REDBELL_SEQ;

CREATE SEQUENCE USERS_SEQ NOCACHE;
CREATE SEQUENCE ACCESS_LOG_SEQ NOCACHE;
CREATE SEQUENCE RETIRE_USERS_SEQ NOCACHE;
CREATE SEQUENCE SLEEP_USERS_SEQ NOCACHE;
CREATE SEQUENCE F_BOARD_SEQ NOCACHE;
CREATE SEQUENCE F_IMAGE_SEQ NOCACHE;
CREATE SEQUENCE F_CMT_SEQ NOCACHE;
CREATE SEQUENCE F_LIKED_SEQ NOCACHE;
CREATE SEQUENCE C_BOARD_SEQ NOCACHE;
CREATE SEQUENCE C_IMAGE_SEQ NOCACHE;
CREATE SEQUENCE C_ATTACH_SEQ NOCACHE;
CREATE SEQUENCE C_CMT_SEQ NOCACHE;
CREATE SEQUENCE C_LIKED_SEQ NOCACHE;
CREATE SEQUENCE Q_BOARD_SEQ NOCACHE;
CREATE SEQUENCE Q_CMT_SEQ NOCACHE;
CREATE SEQUENCE S_GROUP_SEQ NOCACHE;
CREATE SEQUENCE S_CMT_SEQ NOCACHE;
CREATE SEQUENCE S_MEMBER_SEQ NOCACHE;
CREATE SEQUENCE REDBELL_SEQ NOCACHE;
